<a href="https://colab.research.google.com/github/akshita06agrawal/retailmart-data-pipeline/blob/main/RetailMart_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import sqlite3
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#TASK:1

#Create Sales.csv file
sales_data = {
    "sale_id": ["S001", "S002", "S003", "S004", "S005",
                "S006", "S007", "S008", "S009", "S010",
                "S011", "S012", "S013", "S013", "S014"],

    "store_id": ["ST01", "ST02", "ST03", "ST04", "ST05",
                 "ST01", "ST02", "ST03", "ST04", "ST05",
                 "ST06", "ST07", "ST08", "ST08", "ST09"],

    "product_id": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110",
                   "P111", "P112", "P113", "P113", "P114"],

    "quantity": [5, 3, 2, 8, None,
                 4, 6, 7, 5, 10,
                 None, 3, 9, 9, 4],

    "sale_date": ["2026-06-01", "2026-06-01", "2026-06-01",
                  "2026-06-02", "2026-06-02", "2026-06-02",
                  "2026-06-03", "2026-06-03", "2026-06-03",
                  "2026-06-04", "2026-06-04", "2026-06-05",
                  "2026-06-05", "2026-06-05", "2026-06-06"],

    "amount": [125, 180, 90, 240, 600,
               320, None, 245, 175, 200,
               None, 450, 810, 810, 220]
}

sales_df = pd.DataFrame(sales_data)
sales_df.to_csv("sales_data.csv", index=False)

#Load Sales.csv file
sales_df = pd.read_csv('sales_data.csv')
sales_df

   sale_id store_id product_id  quantity   sale_date  amount
0     S001     ST01       P101       5.0  2026-06-01   125.0
1     S002     ST02       P102       3.0  2026-06-01   180.0
2     S003     ST03       P103       2.0  2026-06-01    90.0
3     S004     ST04       P104       8.0  2026-06-02   240.0
4     S005     ST05       P105       NaN  2026-06-02   600.0
5     S006     ST01       P106       4.0  2026-06-02   320.0
6     S007     ST02       P107       6.0  2026-06-03     NaN
7     S008     ST03       P108       7.0  2026-06-03   245.0
8     S009     ST04       P109       5.0  2026-06-03   175.0
9     S010     ST05       P110      10.0  2026-06-04   200.0
10    S011     ST06       P111       NaN  2026-06-04     NaN
11    S012     ST07       P112       3.0  2026-06-05   450.0
12    S013     ST08       P113       9.0  2026-06-05   810.0
13    S013     ST08       P113       9.0  2026-06-05   810.0
14    S014     ST09       P114       4.0  2026-06-06   220.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#Create products.csv file
products_data = {
    "product_id": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110",
                   "P111", "P112", "P113", "P114", "P115"],

    "product_name": ["Parle-G Biscuits", "Amul Butter",
                     "Tata Tea Premium", "Aashirvaad Atta",
                     "Fortune Sunflower Oil", "Maggi Noodles",
                     "Dairy Milk Chocolate", "Britannia Bread",
                     "Surf Excel Detergent", "Good Day Cookies",
                     "India Gate Basmati Rice", "Patanjali Honey",
                     "Colgate Toothpaste", "Lays Chips",
                     "Dabur Chyawanprash"],

    "category": ["Snacks", "Dairy", "Beverages", "Grocery",
                 "Grocery", "Instant Food", "Confectionery",
                 "Bakery", "Household", "Snacks",
                 "Grocery", "Health", "Personal Care",
                 "Snacks", "Health"],

    "price": [25, 60, 45, 30, 120,
              80, 50, 35, 35, 20,
              95, 150, 90, 55, 180]
}

products_df = pd.DataFrame(products_data)
products_df.to_csv("products.csv", index=False)

#Load products.csv file
products_df = pd.read_csv('products.csv')
products_df

   product_id             product_name       category  price
0        P101         Parle-G Biscuits         Snacks     25
1        P102              Amul Butter          Dairy     60
2        P103         Tata Tea Premium      Beverages     45
3        P104          Aashirvaad Atta        Grocery     30
4        P105    Fortune Sunflower Oil        Grocery    120
5        P106            Maggi Noodles   Instant Food     80
6        P107     Dairy Milk Chocolate  Confectionery     50
7        P108          Britannia Bread         Bakery     35
8        P109     Surf Excel Detergent      Household     35
9        P110         Good Day Cookies         Snacks     20
10       P111  India Gate Basmati Rice        Grocery     95
11       P112          Patanjali Honey         Health    150
12       P113       Colgate Toothpaste  Personal Care     90
13       P114               Lays Chips         Snacks     55
14       P115       Dabur Chyawanprash         Health    180

In [ ]:
#Create stores.csv file
stores_data = {
    "store_id": ["ST01", "ST02", "ST03", "ST04", "ST05",
                 "ST06", "ST07", "ST08", "ST09", "ST10",
                 "ST11", "ST12", "ST13", "ST14", "ST15"],

    "store_name": ["RetailMart Jaipur", "RetailMart Delhi",
                   "RetailMart Mumbai", "RetailMart Bengaluru",
                   "RetailMart Kolkata", "RetailMart Chennai",
                   "RetailMart Hyderabad", "RetailMart Pune",
                   "RetailMart Ahmedabad", "RetailMart Lucknow",
                   "RetailMart Chandigarh", "RetailMart Bhopal",
                   "RetailMart Kochi", "RetailMart Indore",
                   "RetailMart Patna"],

    "city": ["Jaipur", "Delhi", "Mumbai", "Bengaluru",
             "Kolkata", "Chennai", "Hyderabad", "Pune",
             "Ahmedabad", "Lucknow", "Chandigarh",
             "Bhopal", "Kochi", "Indore", "Patna"],

    "region": ["North", "North", "West", "South", "East",
               "South", "South", "West", "West", "North",
               "North", "Central", "South", "Central", "East"]
}

stores_df = pd.DataFrame(stores_data)
stores_df.to_csv("stores.csv", index=False)

#Load stores.csv file
stores_df = pd.read_csv('stores.csv')
stores_df

   store_id             store_name        city   region
0      ST01      RetailMart Jaipur      Jaipur    North
1      ST02       RetailMart Delhi       Delhi    North
2      ST03      RetailMart Mumbai      Mumbai     West
3      ST04   RetailMart Bengaluru   Bengaluru    South
4      ST05     RetailMart Kolkata     Kolkata     East
5      ST06     RetailMart Chennai     Chennai    South
6      ST07   RetailMart Hyderabad   Hyderabad    South
7      ST08        RetailMart Pune        Pune     West
8      ST09   RetailMart Ahmedabad   Ahmedabad     West
9      ST10     RetailMart Lucknow     Lucknow    North
10     ST11  RetailMart Chandigarh  Chandigarh    North
11     ST12      RetailMart Bhopal      Bhopal  Central
12     ST13       RetailMart Kochi       Kochi    South
13     ST14      RetailMart Indore      Indore  Central
14     ST15       RetailMart Patna       Patna     East

In [ ]:
# Shape and First 5 rows of each table
print("Sales Data Shape:", sales_df.shape)
print("First 5 rows of Sales Data:")
print(sales_df.head())


print("\n\nProducts Data Shape:", products_df.shape)
print("First 5 rows of Products Data:")
print(products_df.head())


print("\n\nStores Data Shape:", stores_df.shape)
print("First 5 rows of Stores Data:")
print(stores_df.head())

Sales Data Shape: (15, 6)
First 5 rows of Sales Data:
  sale_id store_id product_id  quantity   sale_date  amount
0    S001     ST01       P101       5.0  2026-06-01   125.0
1    S002     ST02       P102       3.0  2026-06-01   180.0
2    S003     ST03       P103       2.0  2026-06-01    90.0
3    S004     ST04       P104       8.0  2026-06-02   240.0
4    S005     ST05       P105       NaN  2026-06-02   600.0


Products Data Shape: (15, 4)
First 5 rows of Products Data:
  product_id           product_name   category  price
0       P101       Parle-G Biscuits     Snacks     25
1       P102            Amul Butter      Dairy     60
2       P103       Tata Tea Premium  Beverages     45
3       P104        Aashirvaad Atta    Grocery     30
4       P105  Fortune Sunflower Oil    Grocery    120


Stores Data Shape: (15, 4)
First 5 rows of Stores Data:
  store_id            store_name       city region
0     ST01     RetailMart Jaipur     Jaipur  North
1     ST02      RetailMart Delhi      Delhi  North
2     ST03     RetailMart Mumbai     Mumbai   West
3     ST04  RetailMart Bengaluru  Bengaluru  South
4     ST05    RetailMart Kolkata    Kolkata   East

In [ ]:
# Missing values
print("\n\nMissing Values in Sales Data:")
print(sales_df.isnull().sum())

print("\nMissing Values in Products Data:")
print(products_df.isnull().sum())

print("\nMissing Values in Stores Data:")
print(stores_df.isnull().sum())

Missing Values in Sales Data:
sale_id       0
store_id      0
product_id    0
quantity      2
sale_date     0
amount        2
dtype: int64

Missing Values in Products Data:
product_id      0
product_name    0
category        0
price           0
dtype: int64

Missing Values in Stores Data:
store_id      0
store_name    0
city          0
region        0
dtype: int64

In [ ]:
#TASK:2

# Count duplicate rows
duplicates = sales_df.duplicated().sum()

print("Number of duplicate rows found:", duplicates)

# Remove duplicates
sales_df = sales_df.drop_duplicates()

print("Number of duplicate rows removed:", duplicates)


# Fill missing values in quantity with 0
sales_df['quantity'] = sales_df['quantity'].fillna(0)

# Remove rows where amount is missing
sales_df = sales_df.dropna(subset=['amount'])

print("\nShape of cleaned DataFrame:", sales_df.shape)



# Convert sale_date to datetime format
sales_df['sale_date'] = pd.to_datetime(sales_df['sale_date'])

# Convert amount to float
sales_df['amount'] = sales_df['amount'].astype(float)

# Check data types
print("\nUpdated Data Types:")
print(sales_df.dtypes)

Number of duplicate rows found: 1
Number of duplicate rows removed: 1

Shape of cleaned DataFrame: (12, 6)

Updated Data Types:
sale_id               object
store_id              object
product_id            object
quantity             float64
sale_date     datetime64[ns]
amount               float64
dtype: object

In [ ]:
#TASK:3


# Merge sales and products data on product_id
merged_df = pd.merge(sales_df, products_df, on='product_id', how='left')

# Merge the above result with stores data on store_id
final_df = pd.merge(merged_df, stores_df, on='store_id', how='left')

print("Final Merged DataFrame:")
print(final_df)


# Calculate total revenue
final_df['total_revenue'] = final_df['quantity'] * final_df['price']

print("\nMean Revenue:", np.mean(final_df['total_revenue']))
print("Maximum Revenue:", np.max(final_df['total_revenue']))
print("Minimum Revenue:", np.min(final_df['total_revenue']))


city_revenue = final_df.groupby('city')['total_revenue'].sum()

# Sort in descending order
city_revenue = city_revenue.sort_values(ascending=False)

print("\nTotal Revenue Generated Per City:")
print(city_revenue)

Final Merged DataFrame:
   sale_id store_id product_id  quantity  sale_date  amount  \
0     S001     ST01       P101       5.0 2026-06-01   125.0
1     S002     ST02       P102       3.0 2026-06-01   180.0
2     S003     ST03       P103       2.0 2026-06-01    90.0
3     S004     ST04       P104       8.0 2026-06-02   240.0
4     S005     ST05       P105       0.0 2026-06-02   600.0
5     S006     ST01       P106       4.0 2026-06-02   320.0
6     S008     ST03       P108       7.0 2026-06-03   245.0
7     S009     ST04       P109       5.0 2026-06-03   175.0
8     S010     ST05       P110      10.0 2026-06-04   200.0
9     S012     ST07       P112       3.0 2026-06-05   450.0
10    S013     ST08       P113       9.0 2026-06-05   810.0
11    S014     ST09       P114       4.0 2026-06-06   220.0

             product_name       category  price            store_name  \
0        Parle-G Biscuits         Snacks     25     RetailMart Jaipur
1             Amul Butter          Dairy     60      RetailMart Delhi
2        Tata Tea Premium      Beverages     45     RetailMart Mumbai
3         Aashirvaad Atta        Grocery     30  RetailMart Bengaluru
4   Fortune Sunflower Oil        Grocery    120    RetailMart Kolkata
5           Maggi Noodles   Instant Food     80     RetailMart Jaipur
6         Britannia Bread         Bakery     35     RetailMart Mumbai
7    Surf Excel Detergent      Household     35  RetailMart Bengaluru
8        Good Day Cookies         Snacks     20    RetailMart Kolkata
9         Patanjali Honey         Health    150  RetailMart Hyderabad
10     Colgate Toothpaste  Personal Care     90       RetailMart Pune
11             Lays Chips         Snacks     55  RetailMart Ahmedabad

         city region
0      Jaipur  North
1       Delhi  North
2      Mumbai   West
3   Bengaluru  South
4     Kolkata   East
5      Jaipur  North
6      Mumbai   West
7   Bengaluru  South
8     Kolkata   East
9   Hyderabad  South
10       Pune   West
11  Ahmedabad   West

Mean Revenue: 254.58333333333334
Maximum Revenue: 810.0
Minimum Revenue: 0.0

Total Revenue Generated Per City:
city
Pune         810.0
Hyderabad    450.0
Jaipur       445.0
Bengaluru    415.0
Mumbai       335.0
Ahmedabad    220.0
Kolkata      200.0
Delhi        180.0
Name: total_revenue, dtype: float64

In [ ]:
#TASK:4

# Create connection with SQLite database
conn = sqlite3.connect('retailmart.db')

# Load DataFrame into SQL table
final_df.to_sql('retail_sales', conn, if_exists='replace', index=False)

print("Data loaded successfully into 'retail_sales' table.")

# Check the table
query = "SELECT * FROM retail_sales LIMIT 5"
result = pd.read_sql(query, conn)

print("\nFirst 5 rows from retail_sales table:")
print(result)

Data loaded successfully into 'retail_sales' table.

First 5 rows from retail_sales table:
  sale_id store_id product_id  quantity            sale_date  amount  \
0    S001     ST01       P101       5.0  2026-06-01 00:00:00   125.0
1    S002     ST02       P102       3.0  2026-06-01 00:00:00   180.0
2    S003     ST03       P103       2.0  2026-06-01 00:00:00    90.0
3    S004     ST04       P104       8.0  2026-06-02 00:00:00   240.0
4    S005     ST05       P105       0.0  2026-06-02 00:00:00   600.0

            product_name   category  price            store_name       city  \
0       Parle-G Biscuits     Snacks     25     RetailMart Jaipur     Jaipur
1            Amul Butter      Dairy     60      RetailMart Delhi      Delhi
2       Tata Tea Premium  Beverages     45     RetailMart Mumbai     Mumbai
3        Aashirvaad Atta    Grocery     30  RetailMart Bengaluru  Bengaluru
4  Fortune Sunflower Oil    Grocery    120    RetailMart Kolkata    Kolkata

  region  total_revenue
0  North          125.0
1  North          180.0
2   West           90.0
3  South          240.0
4   East            0.0

In [ ]:
# Find top 3 products
query = """
SELECT
    product_name,
    SUM(quantity) AS total_quantity_sold
FROM retail_sales
GROUP BY product_name
ORDER BY total_quantity_sold DESC
LIMIT 3;
"""

top_products = pd.read_sql(query, conn)

print("Top 3 Best-Selling Products:")
print(top_products)

Top 3 Best-Selling Products:
         product_name  total_quantity_sold
0    Good Day Cookies                 10.0
1  Colgate Toothpaste                  9.0
2     Aashirvaad Atta                  8.0

In [ ]:
#TASK:5
# Find total revenue per store per day

query = """
SELECT
    store_name,
    sale_date,
    SUM(total_revenue) AS daily_revenue
FROM retail_sales
GROUP BY store_name, sale_date
ORDER BY sale_date, daily_revenue DESC;
"""

revenue_per_store = pd.read_sql(query, conn)

print("Total Revenue per Store per Day:")
print(revenue_per_store)

Total Revenue per Store per Day:
              store_name            sale_date  daily_revenue
0       RetailMart Delhi  2026-06-01 00:00:00          180.0
1      RetailMart Jaipur  2026-06-01 00:00:00          125.0
2      RetailMart Mumbai  2026-06-01 00:00:00           90.0
3      RetailMart Jaipur  2026-06-02 00:00:00          320.0
4   RetailMart Bengaluru  2026-06-02 00:00:00          240.0
5     RetailMart Kolkata  2026-06-02 00:00:00            0.0
6      RetailMart Mumbai  2026-06-03 00:00:00          245.0
7   RetailMart Bengaluru  2026-06-03 00:00:00          175.0
8     RetailMart Kolkata  2026-06-04 00:00:00          200.0
9        RetailMart Pune  2026-06-05 00:00:00          810.0
10  RetailMart Hyderabad  2026-06-05 00:00:00          450.0
11  RetailMart Ahmedabad  2026-06-06 00:00:00          220.0

In [ ]:
# Total number of transactions
total_transactions = final_df.shape[0]

# Total revenue
total_revenue = final_df['total_revenue'].sum()

# Top selling city
city_revenue = final_df.groupby('city')['total_revenue'].sum()
top_city = city_revenue.idxmax()

# Top selling product
product_sales = final_df.groupby('product_name')['quantity'].sum()
top_product = product_sales.idxmax()

# Print summary report
print("------ RetailMart Summary Report ------")
print("Total Transactions :", total_transactions)
print("Total Revenue      :", total_revenue)
print("Top Selling City   :", top_city)
print("Top Selling Product:", top_product)

------ RetailMart Summary Report ------
Total Transactions : 12
Total Revenue      : 3055.0
Top Selling City   : Pune
Top Selling Product: Good Day Cookies

In [ ]:
#TASK:6

def run_pipeline():

    try:
        # Step 1: Load Data
        sales_df = pd.read_csv("sales_data.csv")
        products_df = pd.read_csv("products.csv")
        stores_df = pd.read_csv("stores.csv")

        print("All files loaded successfully.\n")

        # Step 2: Clean Data

        # Remove duplicate rows
        duplicates = sales_df.duplicated().sum()
        sales_df = sales_df.drop_duplicates()
        print(f"{duplicates} duplicate rows removed.")

        # Fill missing quantity values with 0
        sales_df['quantity'] = sales_df['quantity'].fillna(0)

        # Remove rows where amount is missing
        sales_df = sales_df.dropna(subset=['amount'])

        # Convert data types
        sales_df['sale_date'] = pd.to_datetime(sales_df['sale_date'])
        sales_df['amount'] = sales_df['amount'].astype(float)

        print("Data cleaning completed.\n")

        # Step 3: Transform Data

        # Merge DataFrames
        merged_df = pd.merge(
            sales_df,
            products_df,
            on='product_id',
            how='left'
        )

        final_df = pd.merge(
            merged_df,
            stores_df,
            on='store_id',
            how='left'
        )

        # Create total_revenue column
        final_df['total_revenue'] = (
            final_df['quantity'] * final_df['price']
        )

        print("Data transformation completed.\n")

        # Step 4: Load into SQLite Database

        conn = sqlite3.connect("retailmart.db")

        final_df.to_sql(
            "retail_sales",
            conn,
            if_exists='replace',
            index=False
        )

        print("Data loaded successfully into SQLite database.\n")

        print("Pipeline executed successfully!")

        return final_df

    except FileNotFoundError as e:
        print("Error: One or more CSV files are missing.")
        print(e)

    except Exception as e:
        print("An unexpected error occurred:")
        print(e)

final_df = run_pipeline()

All files loaded successfully.

1 duplicate rows removed.
Data cleaning completed.

Data transformation completed.

Data loaded successfully into SQLite database.

Pipeline executed successfully!